### ISSUE TITLE
sudo service iot getdeviceid not working for certain LANG settings

### ISSUE THREAD

**Issue by fhaverkamp** [ibm-messaging/iot-raspberrypi#11]
Hi,

I tried to run some of the tutorials with LANG set to de_DE.UTF-8 and I was unable to get the MAC addr via the described method (ifconfig wlan0 worked of course). Here is what I saw so far. I guess running the daemon might also fail with some LANG settings:

pi@raspberrypi:~/Bluemix $ sudo LANG=en service iot getdeviceid
The device ID is b827eb8d5add
For Real-time visualization of the data, visit http://quickstart.internetofthings.ibmcloud.com/?deviceId=b827eb8d5add
pi@raspberrypi:~/Bluemix $ sudo LANG=de service iot getdeviceid
The device ID is b827eb8d5add
For Real-time visualization of the data, visit http://quickstart.internetofthings.ibmcloud.com/?deviceId=b827eb8d5add
pi@raspberrypi:~/Bluemix $ sudo service iot getdeviceid
The device ID is Adresse
For Real-time visualization of the data, visit http://quickstart.internetofthings.ibmcloud.com/?deviceId=Adresse
pi@raspberrypi:~/Bluemix $ echo $LANG
de_DE.UTF-8

I guess not only German might have this problem. Thanks for having a look if you can fix this up.
Regards

Frank

**Comment by fhaverkamp** [comment]
Please consider using my pull request to fix the reported problem:
https://github.com/ibm-messaging/iot-raspberrypi/pull/12

**Comment by slimmsehli** [comment]
I have the same issue I m from tunisia
